extensions:
    pim-fabric-index:
        module: pim/form/common/index/index

    pim-fabric-index-grid-title:
        module: pim/common/grid-title
        parent: pim-fabric-index
        targetZone: title
        config:
            title: pim_custom_entity.index_title

    pim-fabric-index-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-fabric-index
        targetZone: breadcrumbs
        config:
            tab: pim-menu-reference_data
            item: pim-menu-reference_data-color

    pim-fabric-index-grid-filters-list:
        module: oro/datafilter/filters-list
        parent: pim-fabric-index
        targetZone: filters

    pim-fabric-index-grid-filters-manage:
        module: oro/datafilter/filters-button
        parent: pim-fabric-index
        targetZone: filters

    pim-fabric-index-pagination:
        module: oro/datagrid/pagination-input
        parent: pim-fabric-index
        targetZone: toolbar

    pim-fabric-index-grid:
        module: pim/form/common/index/grid
        parent: pim-fabric-index
        targetZone: content
        config:
            alias: fabric

    pim-fabric-index-create-button:
        module: pim/form/common/index/create-button
        parent: pim-fabric-index
        targetZone: buttons
        aclResourceId: pim_enrich_product_create
        config:
           title:     pim_custom_entity.button.create
           modalForm: pim-fabric-create-modal
