extensions:
    pim-pictogram-index:
        module: pim/form/common/index/index

    pim-pictogram-index-grid-title:
        module: pim/common/grid-title
        parent: pim-pictogram-index
        targetZone: title
        config:
            title: pim_custom_entity.index_title

#    pim-pictogram-index-breadcrumbs:
#        module: pim/common/breadcrumbs
#        parent: pim-pictogram-index
#        targetZone: breadcrumbs
#        config:
#            tab: pim-menu-reference_data
#            item: pim-menu-reference_data-color

    pim-pictogram-index-grid-filters-manage:
        module: oro/datafilter/filters-button
        parent: pim-pictogram-index
        targetZone: filters

    pim-pictogram-index-grid-filters-list:
        module: oro/datafilter/filters-list
        parent: pim-pictogram-index
        targetZone: filters

    pim-pictogram-index-pagination:
        module: oro/datagrid/pagination-input
        parent: pim-pictogram-index
        targetZone: toolbar

    pim-pictogram-index-grid:
        module: pim/form/common/index/grid
        parent: pim-pictogram-index
        targetZone: content
        config:
            alias: pictogram

    pim-pictogram-index-create-button:
        module: pim/form/common/index/create-button
        parent: pim-pictogram-index
        targetZone: buttons
        aclResourceId: pim_enrich_product_create
        config:
           title:     pim_custom_entity.button.create
           modalForm: pim-pictogram-create-modal
