extensions:
    pim-pictogram-index:
        module: pim/common/simple-view
        targetZone: self
        config:
            template: pim/template/product/index
            templateParams:
                gridName: pictogram
        forwarded-events:
            grid_load:start: grid_load:start

    pim-pictogram-index-grid-title:
        module: pim/common/grid-title
        parent: pim-pictogram-index
        targetZone: title
        config:
            title: pim_custom_entity.index_title

    pim-pictogram-index-create-button:
        module: pim/form/common/index/create-button
        parent: pim-pictogram-index
        targetZone: buttons
        aclResourceId: pim_enrich_product_create
        config:
           title:     pim_custom_entity.button.create
           modalForm: pim-pictogram-create-modal

    pim-pictogram-index-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-pictogram-index
        targetZone: breadcrumbs
        config:
            tab: pim-menu-reference_data

    pim-pictogram-index-user-navigation:
        module: pim/menu/user-navigation
        parent: pim-pictogram-index
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pim-pictogram-index-mass-actions:
        module: pim/grid/mass-actions
        parent: pim-pictogram-index
        targetZone: mass-actions
        config:
            label: pim_enrich.entity.product.selected

    pim-pictogram-index-actions-panel:
        module: oro/datagrid/actions-panel
        parent: pim-pictogram-index-mass-actions
        targetZone: actions-panel

    pim-pictogram-index-pagination:
        module: oro/datagrid/pagination-input
        parent: pim-pictogram-index
        targetZone: toolbar

    pim-pictogram-index-grid:
        module: pim/grid/table
        parent: pim-pictogram-index
        targetZone: grid
        config:
            gridName: pictogram
            localeParamName: dataLocale
            datagridLoadUrl: pim_datagrid_load

