connector:
    name: Akeneo Mass Edit Connector
    jobs:
        reference_data_quick_export:
            title: reference_data_quick_export
            type: quick_export
            steps:
                perform:
                    title: csv_reference_data_quick_export
                    services:
                        reader: pim_custom_entity.mass_edit_connector.reader.reference_data
                        processor: pim_custom_entity.mass_edit_connector.processor.reference_data_to_flat_array
                        writer: pim_custom_entity.mass_edit_connector.processor.reference_data_writer
                    parameters:
                        batch_size: 100
