parameters:
    pim_custom_entity.manager.class:          Pim\Bundle\CustomEntityBundle\Manager\Manager
    pim_custom_entity.manager.registry.class: Pim\Bundle\CustomEntityBundle\Manager\Registry

services:
    pim_custom_entity.manager.registry:
        class: '%pim_custom_entity.manager.registry.class%'

    pim_custom_entity.manager:
        class: '%pim_custom_entity.manager.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_custom_entity.updater.custom_entity'
            - '@pim_custom_entity.saver.custom_entity'
            - '@pim_custom_entity.remover.custom_entity'
            - '@pim_custom_entity.normalizer.internal_api.custom_entity'
        tags:
            - { name: pim_custom_entity.manager, alias: default }
