oro_menu_config:
    items:
        pim_reference_data_tab:
            label: pim_menu.tab.reference_data
            uri: '#'
            extras:
                position: 25
            showNonAuthorized: false

oro_titles:
    pim_customentity_index: %%title%%
    pim_customentity_edit: %%title%%
    pim_customentity_create: %%title%%
    pim_customentity_massedit: %%title%%
