parameters:
    pim_custom_entity.versioning.update_guesser.class: Pim\Bundle\CustomEntityBundle\Versioning\UpdateGuesser

services:
    pim_custom_entity.versioning.update_guesser:
        class: '%pim_custom_entity.versioning.update_guesser.class%'
        tags:
            - { name: pim_versioning.update_guesser }
