filter:
    paths:
        - ./*

tools:
    php_mess_detector:
        filter:
            excluded_paths:
                - bin/*
                - spec/*
                - vendor/*
    php_analyzer:
        filter:
            excluded_paths:
                - bin/*
                - spec/*
                - vendor/*
    php_code_sniffer:
        config:
            standard: PSR2
        filter:
            excluded_paths:
                - bin/*
                - spec/*
                - vendor/*
    sensiolabs_security_checker: true
    php_cpd:
        filter:
            excluded_paths:
                - bin/*
                - spec/*
                - vendor/*
    php_loc:
        excluded_dirs:
            - app/
            - bin/
            - vendor/
            - web/
    php_pdepend:
        excluded_dirs:
            - app/
            - bin/
            - vendor/
            - web/
before_commands:
    - 'php -d memory_limit=-1 composer.phar install --prefer-source'
build:
    tests:
        override:
            -
                command: 'bin/phpspec run -f progress -c phpcpec-ci.yml'
                coverage:
                    file: 'coverage.clover'
                    format: 'php-clover'
