extensions:
    acme_custom-menu-reference_data-item-color:
        module: pim/menu/item
        parent: pim-menu-reference_data-navigation-block
        position: 10
        config:
            routeParams:
                customEntityName: color
            title: acme_custom.menu.item.reference_data.color
            to: pim_customentity_index

    acme_custom-menu-reference_data-item-fabric:
        module: pim/menu/item
        parent: pim-menu-reference_data-navigation-block
        position: 20
        config:
            routeParams:
                customEntityName: fabric
            title: acme_custom.menu.item.reference_data.fabric
            to: pim_customentity_index

    acme_custom-menu-reference_data-item-brand:
        module: pim/menu/item
        parent: pim-menu-reference_data-navigation-block
        position: 30
        config:
            routeParams:
                customEntityName: brand
            title: acme_custom.menu.item.reference_data.brand
            to: pim_customentity_index

    acme_custom-menu-reference_data-item-pictogram:
        module: pim/menu/item
        parent: pim-menu-reference_data-navigation-block
        position: 30
        config:
            title: acme_custom.menu.item.reference_data.pictogram
            to: pim_customentity_index
            routeParams:
                customEntityName: pictogram
