Acme\Bundle\CustomBundle\Entity\Color:
    repositoryClass: Pim\Bundle\CustomEntityBundle\Entity\Repository\CustomEntityRepository
    type: entity
    table: acme_reference_data_color
    changeTrackingPolicy: DEFERRED_EXPLICIT
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            unique: true
        sortOrder:
            type: integer
        name:
            type: string
            length: 255
        hex:
            type: string
            length: 255
        red:
            type: integer
        green:
            type: integer
        blue:
            type: integer
    lifecycleCallbacks: {  }
