Acme\Bundle\CustomBundle\Entity\Fabric:
    repositoryClass: Pim\Bundle\CustomEntityBundle\Entity\Repository\CustomEntityRepository
    type: entity
    table: acme_reference_data_fabric
    changeTrackingPolicy: DEFERRED_EXPLICIT
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            unique: true
        sortOrder:
            type: integer
        name:
            type: string
            length: 255
        alternativeName:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
