datagrid:
    color:
        options:
            entityHint: color
            manageFilters: false
        source:
            type: pim_datasource_default
            entity: Acme\Bundle\CustomBundle\Entity\Color
            repository_method: createDatagridQueryBuilder
        columns:
            code:
                label: Code
            name:
                label: Name
            hex:
                label: Hex code
        properties:
            id: ~
            edit_link:
                type: url
                route: pim_customentity_rest_get
                params:
                    - id
                    - customEntityName
            delete_link:
                type: url
                route: pim_customentity_rest_delete
                params:
                    - id
                    - customEntityName
        actions:
            edit:
                type:      navigate
                acl_resource: acme_custom_color_edit
                label:     Edit the reference data
                icon:      edit
                link:      edit_link
                rowAction: true
            delete:
                type:  delete
                acl_resource: acme_custom_color_delete
                label: Delete the reference data
                icon:  trash
                link:  delete_link
        sorters:
            columns:
                code:
                    data_name: rd.code
                name:
                    data_name: rd.name
            default:
                code: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'
        filters:
            columns:
                name:
                    type:      search
                    label:     Name
                    data_name: rd.name
                code:
                    type:      string
                    label:     Code
                    data_name: rd.code

        mass_actions:
            delete:
                type: delete
                label: pim.grid.mass_action.delete
                entity_name: color
                acl_resource: ~
                handler: mass_delete
                className: 'AknButton AknButton--important AknButtonList-item'
                messages:
                    confirm_title: pim_datagrid.mass_action.delete.confirm_title
                    confirm_content: pim_datagrid.mass_action.delete.confirm_content
                    confirm_ok: pim_datagrid.mass_action.delete.confirm_ok
                    success: pim_datagrid.mass_action.delete.success
                    error: pim_datagrid.mass_action.delete.error
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection

            quick_export_csv:
                type: export
                label: pim.grid.mass_action.quick_export.csv_all
                className:  'AknButton AknButton--action AknButtonList-item'
                handler: custom_quick_export
                route: pim_customentity_quickexport
                route_parameters:
                    customEntityName: color
                    _format: csv
                    _contentType: text/csv
                context:
                    withHeader: true
                messages:
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
