# Reference data
## Brand
acme_custom_brand_index:
    type: action
    label: acme_custom.acl.brand.index
    group_name: pim_custom_entity.acl_group.reference_data

acme_custom_brand_create:
    type: action
    label: acme_custom.acl.brand.create
    group_name: pim_custom_entity.acl_group.reference_data

acme_custom_brand_edit:
    type: action
    label: acme_custom.acl.brand.edit
    group_name: pim_custom_entity.acl_group.reference_data

acme_custom_brand_delete:
    type: action
    label: acme_custom.acl.brand.delete
    group_name: pim_custom_entity.acl_group.reference_data

## Color
acme_custom_color_index:
    type: action
    label: acme_custom.acl.color.index
    group_name: pim_custom_entity.acl_group.reference_data

acme_custom_color_create:
    type: action
    label: acme_custom.acl.color.create
    group_name: pim_custom_entity.acl_group.reference_data

acme_custom_color_edit:
    type: action
    label: acme_custom.acl.color.edit
    group_name: pim_custom_entity.acl_group.reference_data

acme_custom_color_delete:
    type: action
    label: acme_custom.acl.color.edit
    group_name: pim_custom_entity.acl_group.reference_data
