custom_entities:
    color:
        entity_class: Acme\Bundle\CustomBundle\Entity\Color
        options:
            edit_fom_extension: pim-color-edit-form

    fabric:
        entity_class: Acme\Bundle\CustomBundle\Entity\Fabric
        options:
            edit_fom_extension: pim-fabric-edit-form

    pictogram:
        entity_class: Acme\Bundle\CustomBundle\Entity\Pictogram
        options:
            edit_fom_extension: pim-pictogram-edit-form

    brand:
        extends: quick_create
        entity_class: Acme\Bundle\CustomBundle\Entity\Brand
        options:
            edit_fom_extension: pim-brand-edit-form
        actions:
            mass_edit:
                form_type: acme_enrich_brand_mass_edit
                service: pim_custom_entity.action.mass_edit
            quick_export:
                service: pim_custom_entity.action.quick_export
