custom_entities:
    color:
        entity_class: Acme\Bundle\CustomBundle\Entity\Color

    fabric:
        entity_class: Acme\Bundle\CustomBundle\Entity\Fabric

    brand:
        extends: quick_create
        entity_class: Acme\Bundle\CustomBundle\Entity\Brand
        actions:
            index:
                acl: acme_enrich_brand_index
                service: pim_custom_entity.action.index
            edit:
                acl: acme_enrich_brand_edit
                form_type: acme_enrich_brand
                service: pim_custom_entity.action.edit
            create:
                acl: acme_enrich_brand_create
                form_type: pim_custom_entity
                service: pim_custom_entity.action.create
            delete:
                acl: acme_enrich_brand_delete
                service: pim_custom_entity.action.delete
            show:
                service: pim_custom_entity.action.show
                template: AcmeCustomBundle:Brand:show.html.twig
            mass_edit:
                form_type: acme_enrich_brand_mass_edit
                service: pim_custom_entity.action.mass_edit
            quick_export:
                service: pim_custom_entity.action.quick_export

    pictogram:
        entity_class: Acme\Bundle\CustomBundle\Entity\Pictogram
        actions:
            index:
                service: pim_custom_entity.action.index
            create:
                service: pim_custom_entity.action.create
                form_type: acme_enrich_pictogram
                form_options:
                    translation_class: Acme\Bundle\CustomBundle\Entity\PictogramTranslation
            edit:
                service: pim_custom_entity.action.edit
                form_type: acme_enrich_pictogram
                form_options:
                    translation_class: Acme\Bundle\CustomBundle\Entity\PictogramTranslation
