extensions:
    pim-brand-edit-form:
        module: pim/form/common/edit-form

    pim-brand-edit-form-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-brand-edit-form
        targetZone: breadcrumbs
        config:
            tab: pim-menu-reference_data
            item: pim-menu-reference_data-brand

    pim-brand-edit-form-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-brand-edit-form
        position: 1000

    pim-brand-edit-form-form-tabs:
        module: pim/form/common/form-tabs
        parent: pim-brand-edit-form
        targetZone: content
        position: 100

    pim-brand-edit-form-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: pim-brand-edit-form
        targetZone: buttons
        position: 50

    pim-brand-edit-form-delete:
        module: pim/group-edit-form/delete
        parent: pim-brand-edit-form-secondary-actions
        targetZone: secondary-actions
        aclResourceId: pim_enrich_group_remove
        position: 100
        config:
            trans:
                title: acme_custom.message.confirmation.remove.brand
                container: pim_enrich.confirmation.delete_item
                success: acme_custom.message.removed.brand
                fail: acme_custom.error.removing.brand
            redirect: pim_customentity_index

    pim-brand-edit-form-save-buttons:
        module: pim/form/common/save-buttons
        parent: pim-brand-edit-form
        targetZone: buttons
        position: 120

    pim-brand-edit-form-state:
        module: pim/form/common/state
        parent: pim-brand-edit-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.group.title

    pim-brand-edit-form-save:
        module: custom_entity/form/common/save-form
        parent: pim-brand-edit-form
        targetZone: buttons
        position: 0
        config:
            updateSuccessMessage: pim_enrich.entity.attribute.info.update_successful
            updateFailureMessage: pim_enrich.entity.attribute.info.update_failed
            notReadyMessage: pim_enrich.entity.attribute.info.field_not_ready
            url: pim_customentity_rest_edit
            route_params:
                customEntityName: brand
            redirectAfter: pim_customentity_edit
            excludedProperties: []

    pim-brand-edit-form-properties-tab:
        module: pim/common/tab
        parent: pim-brand-edit-form-form-tabs
        targetZone: container
        position: 100
        config:
            label: pim_custom_entity.form.tab.properties.title

    pim-brand-edit-form-properties:
        module: pim/common/simple-view
        parent: pim-brand-edit-form-properties-tab
        targetZone: self
        config:
            template: pim/template/form/tab/sections

    pim-brand-edit-form-history:
        module: pim/common/tab/history
        parent: pim-brand-edit-form-form-tabs
        targetZone: container
        position: 110
        config:
            class: group
            title: pim_custom_entity.form.tab.history.title

    pim-brand-edit-form-state:
        module: pim/form/common/state
        parent: pim-brand-edit-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.group.title

    pim-brand-edit-form-properties:
        module: pim/common/simple-view
        parent: pim-brand-edit-form-properties-tab
        targetZone: self
        config:
            template: pim/template/form/tab/sections

    pim-brand-edit-form-properties-common:
        module: pim/common/simple-view
        parent: pim-brand-edit-form-properties
        targetZone: accordion
        position: 100
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: acme_custom.brand.form.tab.properties.section.common
                dropZone: content

    pim-brand-edit-form-properties-code:
        module: pim/attribute-edit-form/properties/text
        parent: pim-brand-edit-form-properties-common
        targetZone: content
        position: 90
        config:
            fieldName: code
            required: true
            readOnly: true
